name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Check for Existing Tags
        id: check-tags
        run: |
          if [ -z "$(git tag -l)" ]; then
            echo "no_tags=true" >> $GITHUB_ENV
          else
            echo "no_tags=false" >> $GITHUB_ENV
          fi

      - name: Generate Release Tag
        run: |
          if [ "${{ env.no_tags }}" = "true" ]; then
            npm run release -- --first-release
          else
            npm run release
          fi

      - name: Generate Release Tag
        run: npm run release

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
